// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYg0Zj7DAd4L92mhsKbZVKxk7w8TbA--w',
    appId: '1:536709969871:web:54a9d8cc14b8fda06d44ba',
    messagingSenderId: '536709969871',
    projectId: 'hackathone-4786c',
    authDomain: 'hackathone-4786c.firebaseapp.com',
    storageBucket: 'hackathone-4786c.firebasestorage.app',
    measurementId: 'G-Y0D051XWH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqlIBgowlLuitBWnjhjmwARer2v_Ad5Q',
    appId: '1:536709969871:android:bb6b832745fd68976d44ba',
    messagingSenderId: '536709969871',
    projectId: 'hackathone-4786c',
    storageBucket: 'hackathone-4786c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1doQtq8L3ziIV7Cg25Q8nngfIn6-m0Q',
    appId: '1:536709969871:ios:591aa47037da98b36d44ba',
    messagingSenderId: '536709969871',
    projectId: 'hackathone-4786c',
    storageBucket: 'hackathone-4786c.firebasestorage.app',
    iosBundleId: 'com.example.hackathoneTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk1doQtq8L3ziIV7Cg25Q8nngfIn6-m0Q',
    appId: '1:536709969871:ios:591aa47037da98b36d44ba',
    messagingSenderId: '536709969871',
    projectId: 'hackathone-4786c',
    storageBucket: 'hackathone-4786c.firebasestorage.app',
    iosBundleId: 'com.example.hackathoneTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYg0Zj7DAd4L92mhsKbZVKxk7w8TbA--w',
    appId: '1:536709969871:web:39a7db3e9657ecd86d44ba',
    messagingSenderId: '536709969871',
    projectId: 'hackathone-4786c',
    authDomain: 'hackathone-4786c.firebaseapp.com',
    storageBucket: 'hackathone-4786c.firebasestorage.app',
    measurementId: 'G-D5BH4LC74N',
  );
}
